// Mock data for flagged listings
// lib/dunmydata.js 
export const flaggedListings = [
    {
      id: "1",
      title: "Macbook Pro 2023",
      category: "Electronics",
      seller: "Alex Johnson",
      sellerEmail: "alex.j@university.edu",
      reason: "Suspected stolen item",
      date: new Date("2023-03-15"),
      price: "$1,200",
      description:
        "Like new MacBook Pro 2023 with M2 chip, 16GB RAM, and 512GB SSD. Only used for 3 months. Comes with original packaging, charger, and AppleCare+ until 2025. Perfect condition with no scratches.",
      image: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      location: "Under the Palms",
      flaggedBy: "Campus Security",
      flagCount: 3,
    },
    {
      id: "2",
      title: "iPhone 14 Pro",
      category: "Electronics",
      seller: "Jamie Smith",
      sellerEmail: "jamie.smith@university.edu",
      reason: "Unrealistic price",
      date: new Date("2023-03-18"),
      price: "$300",
      description:
        "iPhone 14 Pro, 256GB, Graphite. Minor scratches on screen but works perfectly. Includes charger and case.",
      image: "/placeholder.svg?height=600&width=600",
      location: "Library Entrance",
      flaggedBy: "Admin",
      flagCount: 2,
    },
    {
      id: "3",
      title: "Calculus Textbook",
      category: "Books",
      seller: "Taylor Wong",
      sellerEmail: "taylor.w@university.edu",
      reason: "Counterfeit material",
      date: new Date("2023-03-20"),
      price: "$45",
      description: "Calculus: Early Transcendentals, 8th Edition. Barely used, no highlights or notes.",
      image: "/placeholder.svg?height=600&width=600",
      location: "Math Building",
      flaggedBy: "Professor Davis",
      flagCount: 1,
    },
    {
      id: "4",
      title: "Dorm Refrigerator",
      category: "Appliances",
      seller: "Jordan Lee",
      sellerEmail: "jordan.l@university.edu",
      reason: "Prohibited item",
      date: new Date("2023-03-22"),
      price: "$80",
      description: "Mini fridge, 3.2 cubic feet. Perfect for dorm rooms. Used for one semester only.",
      image: "/placeholder.svg?height=600&width=600",
      location: "Dorm C",
      flaggedBy: "Residence Life",
      flagCount: 2,
    },
    {
      id: "5",
      title: "Concert Tickets",
      category: "Entertainment",
      seller: "Morgan Chen",
      sellerEmail: "morgan.c@university.edu",
      reason: "Potential scalping",
      date: new Date("2023-03-25"),
      price: "$150",
      description: "Two tickets to the upcoming campus concert. Section A, Row 3.",
      image: "/placeholder.svg?height=600&width=600",
      location: "Student Union",
      flaggedBy: "Event Committee",
      flagCount: 4,
    },
  ]


 // Mock data for users
export const users = [
{
    id: "1",
    name: "Alex Johnson",
    email: "alex.j@university.edu",
    role: "Student",
    flagCount: 3,
    joinDate: new Date("2022-09-01"),
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "Computer Science",
    year: "3rd Year",
    listings: [
    { id: "101", title: "Macbook Pro 2023", price: "$1,200", status: "Flagged" },
    { id: "102", title: "Computer Science Textbooks", price: "$80", status: "Active" },
    { id: "103", title: "Desk Lamp", price: "$25", status: "Sold" },
    ],
    transactions: [
    { id: "t1", type: "Sale", item: "Wireless Headphones", amount: "$120", date: new Date("2023-02-15") },
    { id: "t2", type: "Purchase", item: "Scientific Calculator", amount: "$45", date: new Date("2023-01-10") },
    ],
    reports: [
    {
        id: "r1",
        reason: "Suspected stolen item",
        item: "Macbook Pro 2023",
        reportedBy: "Campus Security",
        date: new Date("2023-03-15"),
    },
    {
        id: "r2",
        reason: "Misleading description",
        item: "Bluetooth Speaker",
        reportedBy: "Jamie Smith",
        date: new Date("2023-02-20"),
    },
    { id: "r3", reason: "Non-delivery", item: "Textbook", reportedBy: "Taylor Wong", date: new Date("2023-01-25") },
    ],
},
{
    id: "2",
    name: "Jamie Smith",
    email: "jamie.smith@university.edu",
    role: "Student",
    flagCount: 0,
    joinDate: new Date("2022-08-15"),
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "Business",
    year: "2nd Year",
    listings: [
    { id: "201", title: "Business Textbooks", price: "$95", status: "Active" },
    { id: "202", title: "Desk Chair", price: "$60", status: "Active" },
    ],
    transactions: [
    { id: "t3", type: "Sale", item: "Business Calculator", amount: "$30", date: new Date("2023-02-05") },
    ],
    reports: [],
},
{
    id: "3",
    name: "Taylor Wong",
    email: "taylor.w@university.edu",
    role: "Student",
    flagCount: 1,
    joinDate: new Date("2022-09-10"),
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "Mathematics",
    year: "4th Year",
    listings: [
    { id: "301", title: "Calculus Textbook", price: "$45", status: "Flagged" },
    { id: "302", title: "Graphing Calculator", price: "$70", status: "Sold" },
    ],
    transactions: [
    { id: "t4", type: "Sale", item: "Statistics Textbook", amount: "$50", date: new Date("2023-01-20") },
    { id: "t5", type: "Purchase", item: "Desk Organizer", amount: "$15", date: new Date("2023-02-25") },
    ],
    reports: [
    {
        id: "r4",
        reason: "Counterfeit material",
        item: "Calculus Textbook",
        reportedBy: "Professor Davis",
        date: new Date("2023-03-20"),
    },
    ],
},
{
    id: "4",
    name: "Jordan Lee",
    email: "jordan.l@university.edu",
    role: "Student",
    flagCount: 2,
    joinDate: new Date("2022-08-20"),
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "Engineering",
    year: "3rd Year",
    listings: [
    { id: "401", title: "Dorm Refrigerator", price: "$80", status: "Flagged" },
    { id: "402", title: "Engineering Textbooks", price: "$110", status: "Active" },
    { id: "403", title: "Desk Lamp", price: "$20", status: "Sold" },
    ],
    transactions: [
    { id: "t6", type: "Sale", item: "Engineering Calculator", amount: "$60", date: new Date("2023-02-10") },
    { id: "t7", type: "Purchase", item: "Wireless Mouse", amount: "$25", date: new Date("2023-03-05") },
    ],
    reports: [
    {
        id: "r5",
        reason: "Prohibited item",
        item: "Dorm Refrigerator",
        reportedBy: "Residence Life",
        date: new Date("2023-03-22"),
    },
    {
        id: "r6",
        reason: "Item not as described",
        item: "Bluetooth Speaker",
        reportedBy: "Morgan Chen",
        date: new Date("2023-02-15"),
    },
    ],
},
{
    id: "5",
    name: "Morgan Chen",
    email: "morgan.c@university.edu",
    role: "Student",
    flagCount: 4,
    joinDate: new Date("2022-09-05"),
    status: "Active",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "Arts",
    year: "2nd Year",
    listings: [
    { id: "501", title: "Concert Tickets", price: "$150", status: "Flagged" },
    { id: "502", title: "Art Supplies", price: "$65", status: "Active" },
    { id: "503", title: "Drawing Tablet", price: "$200", status: "Sold" },
    ],
    transactions: [
    { id: "t8", type: "Sale", item: "Sketchbook Set", amount: "$40", date: new Date("2023-01-15") },
    { id: "t9", type: "Purchase", item: "Wireless Headphones", amount: "$120", date: new Date("2023-02-20") },
    ],
    reports: [
    {
        id: "r7",
        reason: "Potential scalping",
        item: "Concert Tickets",
        reportedBy: "Event Committee",
        date: new Date("2023-03-25"),
    },
    { id: "r8", reason: "Non-delivery", item: "Art Prints", reportedBy: "Jamie Smith", date: new Date("2023-02-10") },
    {
        id: "r9",
        reason: "Misleading description",
        item: "Camera Lens",
        reportedBy: "Jordan Lee",
        date: new Date("2023-01-30"),
    },
    {
        id: "r10",
        reason: "Prohibited item",
        item: "Software License",
        reportedBy: "IT Department",
        date: new Date("2023-03-10"),
    },
    ],
},
]